---
- hosts: webservers
  become: yes
  tasks:
      - block:
        - name: Install Apache
          yum:
            name: httpd
            state: latest
        - name: install db 
          yum:
            name: mariadb-server
            state: latest
        - name: install php
          yum:
            name: php
            state: latest
        - name: install perl
          yum: 
            name: perl
            state: latest
      - block:   
        - name: httpd start
          service:
            name: httpd
            enabled: true
            state: started
        - name: mariadb start
          service:
            name: mariadb
            enabled: true
            state: started  
